Fixed python error when building from shallow checkout
  File "openMSX/build/executils.py", line 47, in captureStdout
    stderrdata = stderrdata.replace('\r', '')
TypeError: a bytes-like object is required, not 'str'