Fixed compilation error for clang in c++11 mode
I got the following error message:
   src/sound/YMF278.cc:292:2: error: non-constant-expression cannot be narrowed from type
      'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]

So it seems clang is stricter than gcc/vc++ in this aspect. I'm not sure which
compiler is correct. (If clang is correct it means c++11 is not 100% backwards
compatible with c++98). Anyway the fix was very easy.

git-svn-id: file:///openmsx-svn/code/openmsx/trunk@12968 7512d703-071c-0410-b5c2-d2bdd895b7d1