Revert "Use 'static operator()' (new in gcc-13)"
This reverts commit ce9e75f653110b032750d71ee66b8bc954f8e51a.

Works fine with gcc-13 and clang. Doesn't work yet with msvc (compiler
bug?). Seems like 'static operator()' itself does work, but the
'std::invocable' concept doesn't recognize it???

For future reference here's the error message (repeats 100s of times):

D:\a\openMSX\openMSX\src\utils\endian.hh(73,13): error C7602: 'Endian::EndianT': the associated constraints are not satisfied
(compiling source file '../../src/cassette/CassettePlayer.cc')
    D:\a\openMSX\openMSX\src\utils\endian.hh(34,55):
    see declaration of 'Endian::EndianT'
    D:\a\openMSX\openMSX\src\utils\endian.hh(34,27):
    the concept 'std::invocable<Endian::ConvBig<false>,uint16_t>' evaluated to false
        C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\concepts(254,44):
        'invoke': no matching overloaded function found
            C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits(1674,16):
            could be 'unknown-type std::invoke(_Callable &&,_Ty1 &&,_Types2 ...) noexcept(<expr>)'
            C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits(1668,16):
            or 'unknown-type std::invoke(_Callable &&) noexcept(<expr>)'