shaders: Fix TV shader syntax error.
The f suffix is not valid GLSL 1.10, and caused a crash on macOS.

> Uncaught exception: Error(s) compiling shader "tv.vert":
> ERROR: 0:18: 'f' : syntax error: syntax error